// <auto-generated />
namespace EasyERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class migr19 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migr19));
        
        string IMigrationMetadata.Id
        {
            get { return "201411021125327_migr19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
