// <auto-generated />
namespace EasyERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class mig24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig24));
        
        string IMigrationMetadata.Id
        {
            get { return "201411081820528_mig24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
